export default {

  SHOW_MSG: 'MSG:SHOW',
  HIDE_MSG: 'MSG:HIDE',

  FETCH_MSG: 'MSG:FETCH',
  API_FETCH_MSG: 'API:MSG:FETCH',
  API_FETCH_MSG_SUCCESS: 'API:MSG:FETCH:SUCCESS',
  API_FETCH_MSG_FAIL: 'API:MSG:FETCH:FAIL'
};
